name: halaqah

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    name: ðŸš€ Deploy to FTP
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ Get latest code
      uses: actions/checkout@v3

    - name: ðŸ“‚ Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 151.243.222.70
        username: halaqah@zakkal.my.id
        password: halaqah123
        protocol: ftp
        port: 21
        security: loose
        timeout: 60000
        exclude: |
          **/.git*
          **/vendor/**
          **/node_modules/**
          **/.github/**
